Finally join up complement so that script works.
See GitHub issue page #1 for description of thought process.

It passes unit tests:

	$ pytest -q
	...............                                                                        [100%]
	15 passed in 0.04 seconds

Manual test of simple sequence it works:
	$ ./complement.py ATTT
	TAAA

Only thing that remains is to implement the -reverse option.
If this is run get ugly NotImplementedError
	$ ./complement.py -reverse ATTT
	Traceback (most recent call last):
	  File "./complement.py", line 52, in <module>
	    main()
	  File "./complement.py", line 45, in main
	    raise NotImplementedError('reverse option not yet implemented')
	NotImplementedError: reverse option not yet implemented